# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Dev
on:
  push:
    branches-ignore:
      - 'gh-readonly-queue/**'
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  license-header-check:
    runs-on: ubuntu-latest
    name: Check License Header
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      - name: Install HawkEye
      # This CI job is bound by installation time, use `--profile dev` to speed it up
        run: cargo install hawkeye --version 6.2.0 --locked --profile dev
      - name: Run license header check
        run: ci/scripts/license_header.sh

  prettier:
    name: Use prettier to check formatting of documents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f  # v6.1.0
        with:
          node-version: "20"
      - name: Prettier check
        run: |
          # if you encounter error, rerun the command below and commit the changes
          #
          # ignore subproject CHANGELOG.md because they are machine generated
          npx prettier@2.7.1 --write \
            '{datafusion,datafusion-cli,datafusion-examples,dev,docs}/**/*.md' \
            '!datafusion/CHANGELOG.md' \
            README.md \
            CONTRIBUTING.md
          git diff --exit-code

  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          persist-credentials: false
      # Version fixed on purpose. It uses heuristics to detect typos, so upgrading 
      # it may cause checks to fail more often.
      # We can upgrade it manually once a while.
      - name: Install typos-cli
        run: cargo install typos-cli --locked --version 1.37.0
      - name: Run typos check
        run: ci/scripts/typos_check.sh