name: Build
on:
  push:
    tags:
      - v*

jobs:
  build-python-mac-win:
    name: Mac/Win
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-11-24

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin

      - name: Build Python package
        run: cd python && maturin build --release --no-sdist --strip --interpreter python${{matrix.python_version}}

      - name: List wheels
        if: matrix.os == 'windows-latest'
        run: dir python/target\wheels\

      - name: List wheels
        if:  matrix.os != 'windows-latest'
        run: find ./python/target/wheels/

      - name: Archive wheels
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: python/target/wheels/*

  build-manylinux:
    name: Manylinux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build wheels
        run: docker run --rm -v $(pwd):/io konstin2/maturin build --release --manylinux
      - name: Archive wheels
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: python/target/wheels/*

  release:
    name: Publish in PyPI
    needs: [build-manylinux, build-python-mac-win]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
